# ──────────────────────────────────────────────────────────────

        Github = @zusqii

# ──────────────────────────────────────────────────────────────

# ── @ ; Layer Rule ────────────────────────────────────────────

layerrule {
    name = waybar-blur
    match:namespace = waybar
    blur = on
    ignore_alpha = 0.3
}

layerrule {
    name = rofi-blur
    match:namespace = rofi
    blur = on
    ignore_alpha = 0.3
}

# ──────────────────────────────────────────────────────────────
