# ──────────────────────────────────────────────────────────────

        Github = @zusqii

# ──────────────────────────────────────────────────────────────

# ── @ ; General ───────────────────────────────────────────────────────────────────

general {
    gaps_in = 3
    gaps_out = 5
    border_size = 1

    col.active_border   = rgba(a6adc8ff)
    col.inactive_border = rgba(313244cc)

    resize_on_border = false
    allow_tearing    = false
    layout           = dwindle
}


# ── @ ; Decoration ────────────────────────────────────────────────────────────────

decoration {
    rounding       = 10
    rounding_power = 2

    # Window transparency
    active_opacity   = 0.9
    inactive_opacity = 0.80

    shadow {
        enabled      = true
        range        = 4
        render_power = 3
        color        = rgba(1a1a1aee)
    }

    blur {
        enabled           = true
        size              = 6
        passes            = 1
        noise             = 0.00
        contrast          = 1.0
        brightness        = 1.0
        vibrancy          = 0.176
        new_optimizations = true
	ignore_opacity    = true
    }
}

# ── @ ; Layouts ───────────────────────────────────────────────────────────────────

dwindle {
    pseudotile    = true
    preserve_split = true
}

master {
    new_status = master
}

# ── @ ; Misc ──────────────────────────────────────────────────────────────────────

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo   = true
}
