# ─────────────────────────────────────────────────────────────────────────────

#  Github =  @zusqii

# ─────────────────────────────────────────────────────────────────────────────


# ── @ ; Monitors ────────────────────────────────────────────────────────────

	monitor=,preferred,auto,1


# ── @ ; My Programs & Autostart ─────────────────────────────────────────────

	source = ~/.config/hypr/configs/programs.conf


# ── @ ; Environment Variables & Permissions ──────────────────────────────────

	source = ~/.config/hypr/configs/environment.conf

# ── @ ; Keybinds ─────────────────────────────────────────────────────────────

	source = ~/.config/hypr/configs/keybinds.conf

# ── @ ; Look and feel ────────────────────────────────────────────────────────

	source = ~/.config/hypr/configs/looknfeel.conf

# ── @ ; Animations ────────────────────────────────────────────────────────────

	source = ~/.config/hypr/configs/animations.conf

# ── @ ; Layer Rule ────────────────────────────────────────────────────────────

	source = ~/.config/hypr/configs/layers.conf

# ── @ ; Input ─────────────────────────────────────────────────────────────────

	source = ~/.config/hypr/configs/input.conf

# ── @ ; Window Rules ───────────────────────────────────────────────────────────

	source = ~/.config/hypr/configs/windowrule.conf

# ─────────────────────────────────────────────────────────────────────────────
